site_name: _magpie documentation
site_description: 'documentation of _magpie (minimal architecture for the generation of portable interactive experiments)'
site_author: 'Michael Franke'

theme:
    # name: rtd-dropdown
    # Default settings
    collapse_by_default: false
    highlightjs: true
    hljs_languages:
        - javascript
        - elixir
    # Development Settings
    name: null
    custom_dir: 'rtd_dropdown/'

repo_url: https://github.com/magpie-ea/magpie-docs/

nav:
- Designing Experiments:
  - Template views: '01_designing_experiments/01_template_views.md'
  - Custom views: '01_designing_experiments/03_custom_views.md'
  - Life cycles and hooks: '01_designing_experiments/04_lifecycles_hooks.md'
  - Canvas: '01_designing_experiments/05_canvas.md'
  - Progress bars: '01_designing_experiments/06_progress_bars.md'
- server app:
  - Installation: '02_using_the_server_app/01_installation.md'
  - Use: '02_using_the_server_app/02_use.md'
- deploying experiments:
  - Deploy configuration: '03_deploying_experiments/01_configuration.md'
  - Recruitment via MTurk: '03_deploying_experiments/02_recruitment_MTurk.md'  
  - Recruitment via Prolific: '03_deploying_experiments/03_recruitment_Prolific.md'  
  - Hosting on netlify: '03_deploying_experiments/04_hosting_on_netlify.md'
- Misc:
  - Development: 04_development.md
  - About: 05_about.md

plugins:
    - search

copyright: MIT license
markdown_extensions:
    - toc:
        baselevel: 4
