site_name: _babe documentation 
nav:
  - designing experiments:
    - Template views: '01_designing_experiments/01_views.md'
    - Custom views: '01_designing_experiments/02_template_views.md'
    - Miscellaneous: '01_designing_experiments/03_custom_views.md'
    - Life cycles & hooks: '01_designing_experiments/04_lifecycles_hooks.md'
    - Canvas: '01_designing_experiments/05_canvas.md'
    - Complex experiments: '01_designing_experiments/06_complex_experiments.md'
  - server app:
    - Installation: '02_using_the_server_app/01_installation.md'
    - Use: '02_using_the_server_app/02_use.md'
  - deploying experiments:
    - Hosting on netlify: '03_deploying_experiments/01_hosting_on_netlify.md'      
  - Development: 04_development.md
  - About: 05_about.md
theme: readthedocs
site_description: documentation of _babe (basic architecture for browser-based experiments)
site_author: Michael Franke
copyright: MIT license
markdown_extensions:
    - toc:
        baselevel: 2
